//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogicLayer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ServiceMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BusinessLogicLayer.Resources.ServiceMessages", typeof(ServiceMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category not found with ID = {0}.
        /// </summary>
        public static string CategoryNotFound {
            get {
                return ResourceManager.GetString("CategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already category with that name.
        /// </summary>
        public static string CategorySameName {
            get {
                return ResourceManager.GetString("CategorySameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have any wallet. Create one first.
        /// </summary>
        public static string CreateWalletFirst {
            get {
                return ResourceManager.GetString("CreateWalletFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom report {0} - {1}.
        /// </summary>
        public static string CustomReport {
            get {
                return ResourceManager.GetString("CustomReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily report {0}.
        /// </summary>
        public static string DailyReport {
            get {
                return ResourceManager.GetString("DailyReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password does not contain a numeric character.
        /// </summary>
        public static string DigitError {
            get {
                return ResourceManager.GetString("DigitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid length of password hash (64 bytes expected).
        /// </summary>
        public static string InvalidPasswordHashLength {
            get {
                return ResourceManager.GetString("InvalidPasswordHashLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid length of password salt (128 bytes expected).
        /// </summary>
        public static string InvalidPasswordSaltLength {
            get {
                return ResourceManager.GetString("InvalidPasswordSaltLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your token.
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password does not contain a lower case letter.
        /// </summary>
        public static string LowerError {
            get {
                return ResourceManager.GetString("LowerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximal password length is {0} characters.
        /// </summary>
        public static string MaximalLengthError {
            get {
                return ResourceManager.GetString("MaximalLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal password length is {0} characters.
        /// </summary>
        public static string MinimalLengthError {
            get {
                return ResourceManager.GetString("MinimalLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly report {0}.
        /// </summary>
        public static string MonthlyReport {
            get {
                return ResourceManager.GetString("MonthlyReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password does not contain a non-alphanumeric character.
        /// </summary>
        public static string NonAlphanumericError {
            get {
                return ResourceManager.GetString("NonAlphanumericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation not found.
        /// </summary>
        public static string OperationNotFound {
            get {
                return ResourceManager.GetString("OperationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have more than one wallet. Please specify WalletId.
        /// </summary>
        public static string SpecifyWallet {
            get {
                return ResourceManager.GetString("SpecifyWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password does not contain an upper case letter.
        /// </summary>
        public static string UpperError {
            get {
                return ResourceManager.GetString("UpperError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username {0} is already taken.
        /// </summary>
        public static string UsernameTaken {
            get {
                return ResourceManager.GetString("UsernameTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet not found with ID = {0}.
        /// </summary>
        public static string WalletNotFound {
            get {
                return ResourceManager.GetString("WalletNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already wallet with that name.
        /// </summary>
        public static string WalletSameName {
            get {
                return ResourceManager.GetString("WalletSameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly report {0}.
        /// </summary>
        public static string YearlyReport {
            get {
                return ResourceManager.GetString("YearlyReport", resourceCulture);
            }
        }
    }
}
